//
// Created by kamilk on 2/3/24.
//

#ifndef FORU_BAZA_H
#define FORU_BAZA_H
#include <QMap>
#include <QString>

QMap<QString, double> mama {
        {"awokado", 160},
        {"ananas", 33},
        {"banan", 95},
        {"bigos", 119},
        {"biszkopty", 400},
        {"jabłko", 46},
        {"jajko", 150},
        {"daktyle suszone", 277},
        {"daktyle", 277},
        {"frytki", 240},
        {"groszek", 75},
        {"gruszka", 54},
        {"kiwi", 56},
        {"kurczak", 150},
        {"kurki", 23},
        {"advocat", 280},
        {"łosoś", 290},
        {"majonez", 714},
        {"mak", 480},
        {"masło", 735},
        {"mleko", 61},
        {"musztarda", 162},
        {"olej rzepakowy", 884},
        {"ozorki", 130},
        {"papaja", 43},
        {"parówki", 290},
        {"pączki", 376},
        {"pestki dyni", 596},
        {"pasztet", 390},
        {"pierogi ruskie", 166},
        {"pierogi z mięsem", 219},
        {"arbuz", 15},
        {"barszcz", 30},
        {"baton" , 490},
        {"brukselka", 37},
        {"boczek", 520},
        {"bekon", 520},
        {"brokuły", 27},
        {"kajzerka", 220},
        {"bułka maślana", 330},
        {"bułka", 250},
        {"bułka grahamka", 258},
        {"bułka pszenna", 250},
        {"burak", 38},
        {"bułka wrocławska", 293},
        {"buraki zasmażane", 83},
        {"cebula", 37},
        {"cielęcina", 123},
        {"chipsy", 540},
        {"chałka", 250},
        {"chałwa", 530},
        {"cheesburger", 280},
        {"cheeseburger", 280},
        {"hamburger", 280},
        {"halibut", 100},
        {"homar", 85},
        {"indyk", 133},
        {"jogurt owocowy", 80},
        {"kabanosy", 330},
        {"kaczka", 310},
        {"kalafior", 22},
        {"ketchup", 93},
        {"kiełbasa", 300},
        {"smalec", 880},
        {"soja", 880},
        {"sok", 40},
        {"słonecznik", 561},
        {"ser", 380},
        {"ser żółty", 380},
        {"twaróg tłusty", 180},
        {"twaróg", 150},
        {"twaróg półtłusty", 133},
        {"twaróg chudy", 99},
        {"sezamki", 402},
        {"sola", 80},
        {"szynka wieprzowa", 250},
        {"szynka", 250},
        {"brzoskwinia", 46},
        {"brzoskwinie", 46},
        {"brukselka", 110},
        {"cebula", 37},
        {"chleb", 250},
        {"chleb baltonowski", 250},
        {"chleb graham", 230},
        {"chleb żytni", 241},
        {"chleb żytni razowy", 223},
        {"chleb razowy", 213},
        {"chrzan", 67},
        {"cukier", 405},
        {"cytryna", 36},
        {"cukierki", 420},
        {"czarne jagody", 46},
        {"czekolada", 530},
        {"czekolada gorzka", 550},
        {"czekolada biała", 540},
        {"mon cheri", 421},
        {"ferrero rocher", 530},
        {"czosnek", 144},
        {"ćwikła", 41},
        {"czereśnie", 55},
        {"dorsz", 227},
        {"wafelki", 553},
        {"fasola szparagowa", 30},
        {"fasolka po bretońsku", 141},
        {"ziemniaki", 89},
        {"grejpfrut", 31},
        {"gruszki", 54},
        {"gołąbki", 128},
        {"groszek", 80},
        {"groszek zielony", 80},
        {"grześki", 550},
        {"gulasz wołowy", 150},
        {"gulasz", 180},
        {"granat", 65},
        {"dżem niskosłodzony" , 150},
        {"dżem wysokosłodzony" , 200},
        {"dżem truskawkowy" , 150},
        {"dżem brzoswiniowy" , 150},
        {"dżem z czarnej porzeczki" , 150},
        {"dżem morelowy" , 150},
        {"dżem" , 150},
        {"flaki", 90},
        {"flaczki", 90},
        {"flądra", 120},
        {"homar", 92},
        {"pierś z indyka", 94},
        {"udko indyka", 130},
        {"udko kurczaka", 184},
        {"dżem jagodowy", 150},
        {"jagodzianki", 314},
        {"jagodzianka", 314},
        {"jajka", 150},
        {"jajka sadzone", 180},
        {"jajko sadzone", 180},
        {"jajko na miękko", 160},
        {"jajko na twardo", 160},
        {"jajka na miękko", 160},
        {"jajka na twardo", 160},
        {"jogurt owocowy", 90},
        {"kalarepa", 29},
        {"kapusta biała", 29},
        {"kapusta czerwona", 27},
        {"kapusta kwaszona", 12},
        {"kapuśniak", 30},
        {"karp", 110},
        {"karp w galarecie", 138},
        {"kasza manna", 350},
        {"kaszanka", 205},
        {"kawa", 3},
        {"mortadela", 205},
        {"pasztetowa", 384},
        {"kluski lane", 94},
        {"klopsiki", 272},
        {"kiwi", 56},
        {"kiełbasa ślaska", 210},
        {"kiełbasa toruńska", 263},
        {"kotlet mielony", 283},
        {"kotlet schabowy", 351},
        {"krupnik", 40},
        {"makaron", 373}
};


#endif //FORU_BAZA_H
