//
// Created by kamilk on 2/3/24.
//
#include <QMap>
#include <QString>
#ifndef FORU_BAZA_H
#define FORU_BAZA_H


QMap<QString, double> mama {
        {"awokado", 160},
        {"ananas", 33},
        {"banan", 95},
        {"bigos", 119},
        {"biszkopty", 400},
        {"jabłko", 46},
        {"jajko", 150},
        {"daktyle suszone", 277},
        {"daktyle", 277},
        {"frytki", 240},
        {"groszek", 75},
        {"gruszka", 54},
        {"kiwi", 56},
        {"kurczak", 150},
        {"kurki", 23},
        {"advocat", 280},
        {"łosoś", 290},
        {"majonez", 714},
        {"mak", 480},
        {"masło", 735},
        {"mleko", 61},
        {"musztarda", 162},
        {"olej rzepakowy", 884},
        {"ozorki", 130},
        {"papaja", 43},
        {"parówki", 290},
        {"pączki", 376},
        {"pestki dyni", 596},
        {"pasztet", 390},
        {"pierogi ruskie", 166},
        {"pierogi z mięsem", 219},
        {"arbuz", 15},
        {"barszcz", 30},
        {"baton" , 490},
        {"brukselka", 37},
        {"boczek", 520},
        {"bekon", 520},
        {"brokuły", 27},
        {"kajzerka", 220},
        {"bułka maślana", 330},
        {"bułka", 250},
        {"bułka grahamka", 258},
        {"bułka pszenna", 250},
        {"burak", 38},
        {"bułka wrocławska", 293},
        {"buraki zasmażane", 83},
        {"cebula", 37},
        {"cielęcina", 123},
        {"chipsy", 540},
        {"chałka", 250},
        {"chałwa", 530},
        {"cheesburger", 280},
        {"cheeseburger", 280},
        {"hamburger", 280},
        {"halibut", 100},
        {"homar", 85},
        {"indyk", 133},
        {"jogurt owocowy", 80},
        {"kabanosy", 330},
        {"kaczka", 310},
        {"kalafior", 22},
        {"ketchup", 93},
        {"kiełbasa", 300},
        {"smalec", 880},
        {"soja", 880},
        {"sok", 40},
        {"słonecznik", 561},
        {"ser", 380},
        {"ser żółty", 380},
        {"twaróg tłusty", 180},
        {"twaróg", 150},
        {"twaróg półtłusty", 133},
        {"twaróg chudy", 99},
        {"sezamki", 402},
        {"sola", 80},
        {"szynka wieprzowa", 250},
        {"szynka", 250}
        
};


#endif //FORU_BAZA_H
